import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins, Roboto } from 'next/font/google'
import Navbar from './components/Navbar'

const roboto = Roboto({
  subsets: ['latin'],
  weight: '500'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  )
}
